import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

export const coreSlugs = ['codes', 'drive-world', 'how-to-play', 'lucky-crates', 'offline-money', 'cars'];
export const productionOrigin = 'https://dream-car-collection.github.io';
export const readJson = (name) => JSON.parse(readFileSync(`content/generated/${name}.json`, 'utf8'));
export const forbidden = /example\.github\.io|\bstarter\b|\bskeleton\b|placeholder|replace[ -]this|Riftfall Survival|Portal Dark v1|Game site template preview|Yorich|Fact Pack|Evidence ID|generated by|Codex|Claude|ChatGPT|internal research|source confidence|automation platform|SEO research dump|SERP research dump|localhost|127\.0\.0\.1|\/Users\/|\/home\/|[A-Z]:\\(?:Users|Windows|home)\\/i;

export function validate({ prelaunch = false } = {}) {
  const site = readJson('site');
  const home = readJson('home');
  const pages = readJson('pages');
  assert.equal(site.readyForLaunch, !prelaunch, 'Launch readiness must match the QA phase');
  assert.equal(site.hosting.siteUrl, productionOrigin);
  assert.equal(site.hosting.basePath, '');
  assert.equal(site.hosting.customDomain, null);
  assert.equal(site.repositoryUrl, null);
  assert.equal(site.siteName, 'Dream Car Collection Wiki');
  assert.equal(site.theme.appearanceMode, 'legacy-v18');
  assert.equal(site.theme.templateVersion, undefined);
  assert.deepEqual(pages.map(p => p.slug), coreSlugs, 'Exactly six launch pages in navigation order');
  const all = [home, ...pages];
  for (const field of ['slug', 'title', 'description']) assert.equal(new Set(all.map(p => p[field])).size, all.length, `Unique ${field}`);
  const known = new Set(all.map(p => p.slug));
  for (const p of all) {
    assert(p.enabled && p.navVisible, `${p.slug}: enabled navigation`);
    assert(p.title.length <= 60 && p.description.length <= 160, `${p.slug}: metadata length`);
    assert(p.primaryKeyword.trim() && p.hero.heading.trim() && p.hero.lead.trim());
    assert(p.sections.length && p.faq.length, `${p.slug}: sections and FAQ required`);
    assert.equal(p.lastReviewed, '2026-10-03');
    assert.equal(new Set(p.sections.map(s => s.id)).size, p.sections.length, 'Unique section IDs');
    for (const slug of p.relatedSlugs ?? []) assert(known.has(slug), `Unknown related slug: ${slug}`);
    for (const s of p.sections) {
      for (const l of s.links ?? []) assert(known.has(l.slug), `Unknown content link: ${l.slug}`);
      for (const table of [s.table, ...(s.subsections ?? []).map(sub => sub.table)].filter(Boolean)) {
        assert(table.rows.every(row => row.length === table.columns.length), `${p.slug}: table shape`);
      }
    }
    assert(!('factsStatus' in p) && !('sourceNotes' in p), 'Internal content fields removed');
  }
  for (const content of [site, ...all]) assert(!forbidden.test(JSON.stringify(content)), 'No production content residue');
  console.log(`Content validation PASS: homepage and ${pages.length} guides (${prelaunch ? 'prelaunch' : 'production'}).`);
  return { site, home, pages };
}
if (process.argv[1]?.endsWith('validate-content.mjs')) validate({ prelaunch: process.argv.includes('--prelaunch') });
